version: '3'

volumes:
  theinkspot_local_postgres_data: {}
  theinkspot_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_local_django:latest
    container_name: theinkspot_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_production_postgres:latest
    container_name: theinkspot_local_postgres
    volumes:
      - theinkspot_local_postgres_data:/var/lib/postgresql/data:Z
      - theinkspot_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_local_docs:latest
    container_name: theinkspot_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./theinkspot:/app/theinkspot:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/mailhog/mailhog:v1.0.0:latest
    container_name: theinkspot_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/redis:6:latest
    container_name: theinkspot_local_redis

  celeryworker:
    <<: *django
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_local_celeryworker:latest
    container_name: theinkspot_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_local_celerybeat:latest
    container_name: theinkspot_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: 915774586570.dkr.ecr.us-east-1.amazonaws.com/theinkspot/theinkspot_local_flower:latest
    container_name: theinkspot_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
