name: BUILD PUSH IMAGES TO AZURE

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

jobs:
  push-build-azurecr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.4

      - name: Log in to Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: BUILD PUSH IMAGES TO AZURE CR
        run: |
          docker-compose -f local.yml build
          echo "Pushing image to ECR..."
          docker-compose -f local.yml push
